config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, controllers: { 
  	registrations: 'admins/registrations', 
  	sessions: 'admins/sessions'
  }
	devise_scope :admin do
		get 'admins/sign_out', to: 'admins/sessions#destroy'
	end
	get 'posts/show'
	get 'posts/new'
	post 'posts/create'
	get 'posts/index'
	get 'posts/reject'
	get 'posts/invoice'
	post 'posts/accept'
	get 'payments/index'
	post 'posts/rejected_request'
	get 'posts/total_amount'
	get 'payments/new'
	post 'payments/create'
	post 'payments/fine'
	get 'payments/show'
	get 'payments/fine'
	get 'payments/coupon_verification'
	post 'payment/admin_payment'
	post 'transaction_histories/create'
	get 'transaction_histories/new'
	get 'transaction_histories/index'
	get 'deposits/new'
	post 'deposits/create'
	get 'deposits/update'
	get 'deposits/index'
	get 'payments/tot_amount'
	delete 'deposits/destroy'
	get 'payments/admin_payments'
	resources :coupons

	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions'
	}
	root 'welcome#index'
	devise_scope :user do
		get 'users/sign_out', to: 'users/sessions#destroy'
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/deposit.rb
class Deposit < ApplicationRecord
	belongs_to :user
	 validate :validation
	after_update :update_balance 
	def update_balance
		@wallet = self.user.wallet
		if self.status=="approved"
			@transaction_history =TransactionHistory.find_by(reference_id:self.deposit_reference)
			@transaction_history.status = "credited"
			@transaction_history.save
			@wallet.transaction do
				@wallet.with_lock do 
					@wallet.balance = @wallet.balance+self.amount 
					@wallet.save
					self.user.wallet.balance
				end
			end
		end
	end

	private def validation
		if  status_was.eql?"approved" or status_was.eql?"rejected"
			errors.add(:status,"you have already updated") 
		end
	end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
	def index
		@deposits = current_user.deposits
	end
	def new
		@deposit = Deposit.new
	end
	
	def create
		if current_user.deposits.where("status = ?","pending").present?
			redirect_to deposits_new_path
			flash[:alert] ="You have pending request, please wait for some time"
		else
			loop do 
				@transaction_reference = ( "deposit" + [*(0..9)].sample(10).join.to_s )
				break @transaction_reference unless TransactionHistory.exists?(reference_id: @transaction_reference)
			end
			deposit = Deposit.new
			deposit.amount = params[:amount]
			deposit.status = "pending"
			deposit.user_id =current_user.id
			deposit.deposit_reference =@transaction_reference
			deposit.save
			redirect_to deposits_new_path
			flash[:notice] ="Successfully Requested deposit"
			
			@transaction_history = TransactionHistory.new()
			@transaction_history.user_id = current_user.id
			@transaction_history.reference_id = @transaction_reference
			@transaction_history.status = "pending"
			@transaction_history.current_wallet_amount = current_user.wallet.balance
			@transaction_history.save
		end
	end

	def update
		@deposit = Deposit.find(params[:id])
		if status.present?
			@deposit.status = "approved"
			@deposit.save
		end
	end
	def destroy
		@deposit = Deposit.find(params[:id])
		@deposit.destroy
		flash[:alert]= "Deposit successfully deleted"
		redirect_to deposits_new_path
	end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/index.html.erb
<div class="container">
<%if @deposits.present?%>
<h1>Deposits</h1>
<table class="table">
	<thead class="thead-dark">
	<tr>
		<!-- <th>Reference id</th> -->
		<th>amount</th>
		<th>status</th>
		<!-- <th>Wallet amount</th> -->
	</tr>
	</thead>
	<tbody>
	<%@deposits.all.each do |deposit|%>
		<tr>
			<!-- <td><%#= deposit.reference_id%></td> -->
			<td><%= deposit.amount%></td>
			<td><%= deposit.status %></td>
			<%if deposit.status =="pending"%>
			<!-- <td><%#= deposit.wallet_amount%></td> -->
			<td><%=link_to "delete request",deposits_destroy_path(:id=>deposit.id), method: :delete, remote: true %><%end%></td>
		</tr>
	<% end %>
	</tbody>
</table>
<%else%>
<h4>There are no deposits present</h4>
<%end%>
</div>

app/views/deposits/new.html.erb
<div class ="container">
	<h3>Request for deposit an amount</h3> 
<%= form_with url: deposits_create_path, local: true  do |form| %>
<br>
<div class="field">
	<%= form.label :amount %>
	<%= form.text_field :amount %>
	<%= form.submit "submit" %>

</div>
	<%= link_to 'Deposit History',deposits_index_path %>


<% end %>
</div>