config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, controllers: { 
  	registrations: 'admins/registrations', 
  	sessions: 'admins/sessions'
  }
	devise_scope :admin do
		get 'admins/sign_out', to: 'admins/sessions#destroy'
	end
	get 'posts/show'
	get 'posts/new'
	post 'posts/create'
	get 'posts/index'
	get 'posts/reject'
	get 'posts/invoice'
	post 'posts/accept'
	get 'payments/index'
	post 'posts/rejected_request'
	get 'posts/total_amount'
	get 'payments/new'
	post 'payments/create'
	post 'payments/fine'
	get 'payments/show'
	get 'payments/fine'
	get 'payments/coupon_verification'
	post 'payment/admin_payment'
	post 'transaction_histories/create'
	get 'transaction_histories/new'
	get 'transaction_histories/index'
	get 'deposits/new'
	post 'deposits/create'
	get 'deposits/update'
	get 'deposits/index'
	get 'payments/tot_amount'
	delete 'deposits/destroy'
	get 'payments/admin_payments'
	resources :coupons

	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions'
	}
	root 'welcome#index'
	devise_scope :user do
		get 'users/sign_out', to: 'users/sessions#destroy'
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :request
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def index
		@posts = current_user.posts.order( 'id ASC' )
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.words = @post.text.split(' ').size
		@post.per_word_amount =PaymentCharge.first.per_word_amount
		@user_wallet = current_user.wallet
		@amount = @post.words.to_f * @post.per_word_amount.to_f
		if @post.words > 1
			if @user_wallet.balance < @amount
				redirect_to posts_new_path,alert: "You don't have enough balance"
			else
				loop do 
				@payment_reference = ( "payment" + [*(0..9)].sample(10).join.to_s )
				break @payment_reference unless Payment.exists?(reference_id: @payment_reference)
				end
					@payment                        = Payment.new
					@payment.user_id                = @post.user_id
					@payment.amount                 = @amount
					@payment.status                 = "pending"
					@payment.reference_id           = @payment_reference
				@user_wallet.transaction do
					@user_wallet.with_lock do 
						@user_wallet.balance = @user_wallet.balance.to_f -  @amount 
						@user_wallet.save

						@user_wallet.hold_amount = @user_wallet.hold_amount.to_f + @amount
						@user_wallet.save
					end
				end
				# creating transaction history
				@transaction_history = TransactionHistory.new()
				@transaction_history.user_id = current_user.id
				@transaction_history.reference_id = @transaction_reference
				@transaction_history.status = "credited"
				@transaction_history.payment_id = @payment.reference_id
				@transaction_history.current_wallet_amount = @user_wallet.balance
				@transaction_history.save
				@post.save
				@payment.post_id = @post.id
				@payment.status = "success"
				@payment.paid_amount = @payment.amount
				@payment.save
				AdminMailer.admin_notify_email(@post).deliver rescue nil
				redirect_to payments_new_path(:id=>@post.id),notice: "Your post has been successfully saved"
			end
		else
			redirect_to posts_new_path,alert: "Please enter text"	
		end
	end

	# after user satisified with the updated_text
	def accept
		@post = Post.find(params[:id])
		@user_wallet = current_user.wallet
		@request = Request.where("post_id=? AND status=?",@post.id,"completed").first
		@user_payment =Payment.where("post_id=? AND user_id=?",@post.id,current_user.id).first
		# comparing two string words
		s1 = @post.text.split(' ')
		s2 = @post.updated_text.split(' ')
		diff = s2 - s1
		# getting count of different words
		@post.words =diff.count
		p @post.words.inspect
			loop do 
				@payment_reference = ( "success" + [*(0..9)].sample(10).join.to_s )
				break @payment_reference unless Payment.exists?(reference_id: @payment_reference)
			end

			# user return payment
			@payment                  = Payment.new()
			@payment.amount           = @post.words * PaymentCharge.first.per_word_amount.to_f
			@payment.reference_id     = @payment_reference
			@payment.status           = "refund"
			@payment.user_id          = current_user.id
			@payment.post_id          = @post.id
			# checking if coupon is present  
				if @user_payment.discount_id.present?
					@coupon = Coupon.find(@user_payment.discount_id) 
					@coupon_redemption = CouponRedemption.where("coupon_id =? AND user_id=?", @coupon.id,current_user.id).first
					@payment.discount_id      = @coupon.id
					@payment.payment_type     = "debited"
					# if coupon type is percentage
					if @coupon.coupon_type == "percentage"
							percentage_amount = @payment.amount.to_f/100.0 * @coupon.percentage.to_f
							# if coupon percentage amount is greater than coupon limit amount
							if percentage_amount.to_f > @coupon.amount.to_f
								@payment.discount_amount  = @coupon.amount.to_f
							else
								@payment.discount_amount = percentage_amount.to_f
							end
					else
						# if coupon type is amount 
						if  @payment.amount.to_f > @coupon.amount.to_f
							@payment.discount_amount  = @coupon.amount.to_f
						else
							@payment.discount_amount  = @payment.amount.to_f
						end
					end
					@user_return_amount        = @user_payment.paid_amount.to_f - @payment.amount.to_f + @payment.discount_amount.to_f
				else 
					@user_return_amount        = @user_payment.paid_amount.to_f - @payment.amount.to_f 
				end
			@payment.amount            = @user_payment.paid_amount.to_f - @user_return_amount.to_f
			@payment.paid_amount       = @user_return_amount.to_f
			@balance_amount            = @user_payment.paid_amount.to_f - @user_return_amount.to_f
			@user_wallet               = User.find(@post.user_id).wallet
			@user_wallet.transaction do
				@user_wallet.with_lock do 
					@user_wallet.hold_amount = @user_wallet.hold_amount.to_f -  @user_return_amount.to_f
					@user_wallet.save

					@user_wallet.balance = @user_wallet.balance.to_f + @user_return_amount.to_f
					@user_wallet.save
				end
			end
			@payment.save

			# payment for super admin commission to successful proof reading 
			@super_admin_payment               = Payment.new()
			@super_admin_payment.admin_id      = Admin.find_by(:role=>"Super Admin").id
			@super_admin_payment.amount        = PaymentCharge.first.commission_percentage.to_f/100 * @payment.amount.to_f.round(2)
			@super_admin_payment.reference_id  = @payment_reference
			@super_admin_payment.status        = "completed"
			@super_admin_payment.post_id       = @post.id
			@super_admin_payment.paid_amount   = @super_admin_payment.amount.to_f
			@super_admin_wallet                = Admin.find_by(:role=>"Super Admin").wallet
			@super_admin_wallet.transaction do
					@super_admin_wallet.with_lock do 
						@user_wallet.hold_amount = @user_wallet.hold_amount.to_f -  @super_admin_payment.paid_amount.to_f
						@user_wallet.save

						@super_admin_wallet.balance = @super_admin_wallet.balance.to_f + @super_admin_payment.paid_amount.to_f
						@super_admin_wallet.save
					end
				end
			@super_admin_payment.save
			
			# payment for proofreader amount 
			@payment2               = Payment.new()
			@payment2.admin_id      = @request.admin_id
			@payment2.amount        = @payment.amount.to_f - @super_admin_payment.paid_amount.to_f
			@payment2.reference_id  = @payment_reference
			@payment2.status        = "completed"
			@payment2.post_id       = @post.id
			@payment2.paid_amount   = @payment2.amount
			@admin_wallet          = Admin.find(@request.admin_id).wallet
			@admin_wallet.transaction do
				@admin_wallet.with_lock do 
					@user_wallet.hold_amount = @user_wallet.hold_amount.to_f -  @payment2.paid_amount.to_f
					@user_wallet.save

					@admin_wallet.balance = @admin_wallet.balance.to_f + @payment2.paid_amount.to_f
					@admin_wallet.save
				end
			end
			@payment2.save
			@post.status ="completed"
			@post.save
			@request.status="completed"
			@request.save
			redirect_to posts_index_path,notice: "Thank you ,Please visit again"
	end

	# if user rejected the updated text
	def reject
		@post =Post.find(params[:id])
		@request =Request.find_by(post_id: @post.id)
	end

	#  reason for the rejection of updated text
	def rejected_request
		@post =Post.find(params[:id])
		@request = Request.where("post_id=? AND status=?", @post.id,"completed").first
		if params[:reason].blank?
			flash[:alert]="Please provide the reason"
			redirect_to posts_reject_path(id:@post.id) 
		else
			@request.reason = params[:reason]
			@request.status = "reserved"
			@request.update(params.permit(:reason,:status))
			UserMailer.post_rejected_email(@request).deliver
			redirect_to posts_index_path
		end
	end

	# displaying the post
	def show
		@post =Post.find(params[:id])
		@request = Request.where("post_id=? AND status=?",@post.id,"completed").first
	end
	# using to calculate the total amount
	def total_amount
		@result = (params[:words].to_i*PaymentCharge.first.per_word_amount).to_i
		respond_to do |format|
			format.html
			format.json {render :json=>@result}
		end
	end
	# invoice for the post
	def invoice
		@post = Post.find(params[:id])
		@request= Request.find_by(post_id:@post.id)
		@payment = Payment.find_by("user_id = ? AND post_id = ? AND status = ?",@post.user_id,@post.id,"success")
		@payment1 = Payment.find_by("user_id = ? AND post_id = ? AND status = ?",@post.user_id,@post.id,"refund")
		respond_to do |format|
			format.html
            format.pdf do
               render pdf: "invoice",
                template: "posts/_form.html.erb",
                layout: "pdf.html",
                disposition: 'attachment'
            end
        end
	end

	def post_params
		params.require(:post).permit(:text,:user_id,:words,:status,:updated_text,:per_word_amount,:reason)
	end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.erb
<div style="margin:5% 40% 0% 33%;float:left; width:500px; box-shadow:0 0 3px #aaa; height:auto;color:#666;">
	 <div style="width:100%; padding:10px; float:left; background:#1ca8dd; color:#fff; font-size:30px; text-align:center;">Invoice
	 </div>
		<div style="width:100%; padding:0px 0px;border-bottom:1px solid rgba(0,0,0,0.2);float:left;">
				<div style="width:30%; float:left;padding:10px;">
					 
						<span style="font-size:14px;float:left; width:100%;">
								<%=User.find(@post.user_id).user_name%>
						</span>
			 <span style="font-size:14px;float:left;width:100%;">
								
						</span>
			<span style="font-size:14px;float:left;width:100%;">
				<%=User.find(@post.user_id).email%>
			</span>
				</div>
		
				<div style="width:40%; float:right;padding:">
						<span style="font-size:14px;float:right;  padding:10px; text-align:right;">
								<b>Date : </b><%=@post.updated_at%>
						</span>
			<span style="font-size:14px;float:right;  padding:10px; text-align:right;">
							 <b> </b>
						</span>
				</div>
		</div>
				
		<div style="width:100%; padding:0px; float:left;">
			<div style="width:100%;float:left;background:#efefef;">
				<span style="float:left; text-align:left;padding:10px;width:50%;color:#888;font-weight:600;">
				Description
				</span>
				<span style="font-weight:600;float:left;padding:10px ;width:10%;color:#888;text-align:right;">
				 words
				</span>
				 <span style="font-weight:600;float:left;padding:10px ;width:40%;color:#888;text-align:right;">
					Amount
				</span>
			</div>
		
			<div style="width:100%;float:left;">
				<h3>User text details</h3>
						<span style="float:left; text-align:left;padding:10px;width:50%;color:#888;">
						amount per word : <%= @post.per_word_amount.to_f%>
				</span>
				<span style="float:left; text-align:left;padding:10px;width:10%;color:#888;">
						<%= @post.text.split(" ").size%>
				</span>
				 <span style="font-weight:normal;float:left;padding:10px ;width:40%;color:#888;text-align:right;">
					 <%=@payment.amount%>
				</span>
			</div>
			<h3>proof readed text Details</h3>
		 <div style="width:100%;float:left;">
					<span style="float:left; text-align:left;padding:10px;width:50%;color:#888;">
					amount per word : <%=@post.per_word_amount.to_f%>
					<span style="font-size:10px; float:left; width:100%;">
					</span>
				</span>
				 <span style="font-weight:normal;float:left;padding:10px ;width:10%;color:#888;text-align:right;">
						<%= @post.words%>
				</span>
				<span style="font-weight:normal;float:left;padding:10px ;width:40%;color:#888;text-align:right;">
						<%=@post.per_word_amount.to_f * @post.words %>
				</span>
			</div>
		<%if @payment1.discount_id.present?%>
				 <div style="width:100%;float:left; background:#fff;">
				 <span style="font-weight:600;float:right;padding:10px 0px;width:40%;color:#666;text-align:center;">
					 Discount Amount:<%=@payment1.discount_amount.round(2)%>
				</span>
			</div>
			<%end%>
			<div style="width:100%;float:left; background:#fff;">
				 <span style="font-weight:600;float:right;padding:10px 0px;width:40%;color:#666;text-align:center;">
					 Refund Amount:<%=@payment1.paid_amount.round(2)%>
				</span>
			</div>
			<div style="width:100%;float:left; background:#fff;">
				 <span style="font-weight:600;float:right;padding:10px 0px;width:40%;color:#666;text-align:center;">
					 Amount paid:<%=@payment1.amount.round(2)%>
				</span>
			</div>

		</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="col-xs-12 text-right">   
				<div class="next">
					<%= link_to "New Post",posts_new_path,class: "btn btn-sm btn-success"%>
					</button>
				</div>
		</div>
<table class="table">
	<thead class="thead-dark">
		<tr>
			<th scope="col">Text</th>
			<th scope="col">words</th>
			<th scope="col">Status</th>
			<th scope="col">Payment Status</th>
			<th scope="col">Post Details</th>
			<th scope="col">Payment Details</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.all.each do |post|%>
		<tr>
			<td><%=post.text%></td>
			<td><%=post.text.split(" ").size%></td>
			<td><%=post.status%></td>
			<%payment = Payment.find_by("post_id = ? AND status=?", post.id,"success")%>
			<%if payment.present?%>
			<td><%=payment.status%></td>
			<%else%>
				<td>pending</td>
			<%end%>
			<td><%=link_to "view",posts_show_path(:id=>post.id)%></td>
			<td>
			<%if payment.present?%>
			 <%=link_to "payment",payments_show_path(:post_id=>post.id)%>
			<%end%>
			</td>
			<td>
			<%if post.status=="completed"%>
			<%=link_to "invoice",posts_invoice_path(:id=>post.id)%>
			<%end%>
			</td>
		</tr>
		<%end%>
	</tbody>
</table>
<br>
</div>

app/views/posts/invoice.html.erb
<%= link_to 'Download invoice', posts_invoice_path(:id=>@post.id,format: 'pdf'),class:"btn btn-primary float-right"%>
<%= render "posts/form"%>

app/views/posts/new.html.erb
<div class="container-fluid">
<div class="container" >
	<div class="row-auto">
		<div class="col-md-6 mx-auto mb-5">

		<%= form_with(model: @post, url: posts_create_path(@post), method: "post", remote: true) do |f| %>
			<h3>Enter a text </h3>
			<div id="word-count-container">
			<%= f.text_area :text ,class: "form-control", :id => "no-of-words", :keyup=>"updatecount()"%>
			</div>
			<div class="col-md-6">
				<h4>number of words:<span id="word-count"></span></h4>
			</div>
			<div class="col-md-2">
				<h4>Amount(₹):<span id="result"></span></h4>
			</div>
			<div class="col-md-8">
				<%= f.submit "Submit" ,class: "btn btn-primary btn-lg"%>
			</div>
		<% end %>
		</div>
	</div>
</div>
</div> 



<script type="text/javascript">
	
 $(document).keyup(function() {
	 var wordCount = $("#no-of-words").val().trim().split(/\s+/).length;
	 $("#word-count").html(wordCount);

	  $.ajax({    
		type: "GET",
		url: "total_amount",
		dataType: "json",
		data: { 
		"words": wordCount
		 },
		success: function(response){ 
			var obj = JSON.stringify(response);
		 $("#result").html(obj)     
		}

	});
});

</script>

app/views/posts/reject.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
		<div class="card text-white bg-dark mb-4" style="max-width: 18rem;">
			<div class="card-header">Post(<%=@post.words%>)</div>
			<div class="card-body">
				<p class="card-text"><%=@post.text%></p>
			</div>
		</div>
		</div>
		<div class="col-sm-6">
		<div class="card text-white bg-dark mb-4" style="max-width: 18rem;">
			<div class="card-header">Post(<%=@post.words%>)</div>
			<div class="card-body">
				<p class="card-text"><%=@post.updated_text%></p>
			</div>
		</div>
		</div>
	</div>
		<h3>Please provide the reason</h3>
		<%= form_with url:posts_rejected_request_path(:id=>@post.id)  do |f|%>
		<div class="row">
			<div class="col-md-4 mx-auto mb-5">
				<%= f.text_area :reason,class: "form-control"%>
				<%= f.submit "Reject",class: "btn btn-lg"%>
			</div>
		</div>
		<%end%>
	
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
		<div class="card text-white bg-dark mb-4" style="max-width: 18rem;">
			<div class="card-header">Post(<%=@post.words%>)</div>
			<div class="card-body">
				<p class="card-text"><%=@post.text%></p>
			</div>
		</div>
		</div>
		<div class="col-sm-6">

		<%if  @request.present? && @request.status=="completed"%>
		<%if @post.updated_text.present?%>
		<div class="card text-white bg-dark mb-4" style="max-width: 18rem;">
			<div class="card-header">Post(<%=@post.words%>)</div>
			<div class="card-body">
				<p class="card-text"><%=@post.updated_text%></p>
			</div>
		</div>
		</div>
		<%end%>
		<%if !Payment.find_by(post_id:@post.id).discount_id.present?%>
		<%if @post.status != "completed"%>
		<h4>Before submitting apply coupon <%=link_to "add coupon",payments_show_path(:post_id=>@post.id)%></h4>
		<%end%>
		<%end%>
		<%if @post.status != "completed"%>
		<div class="col-md-8">
			<%= link_to "Accept",posts_accept_path(:id=>@post.id),class: "btn btn-success",method: :post %>
			<%= link_to "Reject", posts_reject_path(:id=>@post.id),class: "btn btn-danger "%>
			</div>
			<%end%>
		<%end%>
	</div>
</div>